version: "3.8"

# Stack TaktChat com ATUALIZAÇÕES RÁPIDAS (volumes montados)
# 
# Esta stack monta o código via volumes, permitindo atualizações rápidas
# apenas com git pull + reiniciar serviço (sem build de imagem Docker)
#
# ⚠️ PRÉ-REQUISITO OBRIGATÓRIO no servidor VPS:
# 1. Clonar repositório completo:
#    git clone https://github.com/zanon-alive/taktchat.git /root/taktchat
# 
# 2. Instalar dependências do backend:
#    cd /root/taktchat/backend
#    npm install --legacy-peer-deps
#
# 3. Instalar dependências do frontend (opcional - será feito automaticamente):
#    cd /root/taktchat/frontend
#    npm install --legacy-peer-deps
#
# 4. Verificar estrutura:
#    ls -la /root/taktchat/backend/package.json
#    ls -la /root/taktchat/frontend/package.json
#
# ⚠️ ATUALIZAÇÕES RÁPIDAS:
# cd /root/taktchat
# git pull origin main
# cd backend && npm install --legacy-peer-deps  # Se houver novas dependências
# docker service update --force taktchat_taktchat-backend
# docker service update --force taktchat_taktchat-frontend  # Se houver mudanças no frontend
#
# BENEFÍCIOS:
# - Atualização em segundos (apenas git pull + restart)
# - Não precisa fazer build de imagem Docker
# - Ideal para desenvolvimento e atualizações frequentes

services:
  # Serviço de migração e seed do banco de dados (executa uma vez)
  # Executa migrações primeiro, depois os seeds iniciais
  taktchat-migrate:
    image: node:20-bookworm-slim
    hostname: "{{.Service.Name}}.{{.Task.Slot}}"
    networks:
      - app_network
    volumes:
      - /root/taktchat/backend:/usr/src/app:ro  # Código do backend (read-only)
      - taktchat_node_modules:/usr/src/app/node_modules  # Dependências isoladas
      - /root/stacks/scripts/taktchat-migrate-startup.sh:/usr/local/bin/taktchat-migrate-startup.sh:ro  # Script de startup
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres_postgres
      - DB_PORT=5432
      - DB_NAME=taktchat_database
      - DB_USER=taktchat_user
      - DB_PASS=T4ktch4tUs3r@2025
      - DB_DIALECT=postgres
      - PUPPETEER_SKIP_DOWNLOAD=true  # Pular download do Chromium (servidor ARM64)
      - NODE_OPTIONS=--max-old-space-size=512
    command:
      - /bin/sh
      - /usr/local/bin/taktchat-migrate-startup.sh
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: none  # Não reiniciar após conclusão (executa uma vez)
      resources:
        limits:
          cpus: "0.25"
          memory: 768M

  taktchat-backend:
    image: node:20-bookworm-slim
    hostname: "{{.Service.Name}}.{{.Task.Slot}}"
    networks:
      - app_network
      - traefik_public
    volumes:
      - /root/taktchat/backend:/usr/src/app  # Código do backend (read-write necessário para montar public/)
      - taktchat_node_modules:/usr/src/app/node_modules  # Dependências isoladas
      - taktchat_media:/usr/src/app/public  # Uploads e arquivos públicos
      - taktchat_tsc_cache:/tmp  # Cache de compilação TypeScript
      - /root/stacks/scripts/taktchat-backend-startup.sh:/usr/local/bin/taktchat-backend-startup.sh:ro  # Script de startup
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
      - BACKEND_URL=https://taktchat-api.alivesolucoes.com.br
      - FRONTEND_URL=https://taktchat.alivesolucoes.com.br,https://taktchat.com.br
      - DB_HOST=postgres_postgres
      - DB_PORT=5432
      - DB_NAME=taktchat_database
      - DB_USER=taktchat_user
      - DB_PASS=T4ktch4tUs3r@2025
      - DB_DIALECT=postgres
      - JWT_SECRET=04a6ba1d382bcf1e76befc94a75dd687
      - JWT_REFRESH_SECRET=b97a351da95ba6ba8dedafba553f5012
      - REDIS_URI=redis://:z9w5TbZ1mZUHtAfzkbBi@redis_redis:6379
      - REDIS_URI_ACK=redis://:z9w5TbZ1mZUHtAfzkbBi@redis_redis:6379
      - REDIS_URI_MSG_CONN=redis://:z9w5TbZ1mZUHtAfzkbBi@redis_redis:6379
      - SOCKET_FALLBACK_NS_BROADCAST=true
      - PUPPETEER_SKIP_DOWNLOAD=true  # Pular download do Chromium (servidor ARM64)
      - NODE_OPTIONS=--max-old-space-size=768  # Heap do Node.js para compilação TypeScript
    command:
      - /bin/sh
      - /usr/local/bin/taktchat-backend-startup.sh
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.75"
          memory: 1536M  # Precisa compilar TypeScript em runtime
        # Reservations comentadas temporariamente para evitar 'task has not been scheduled'
        # Se houver recursos suficientes, descomente:
        # reservations:
        #   cpus: "0.3"
        #   memory: 384M

      update_config:
        parallelism: 1
        delay: 30s
        order: stop-first
        failure_action: pause  # Pausar em caso de falha para análise (não fazer rollback)
        monitor: 60s

      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 2  # Limitar a 2 tentativas para análise de logs
        window: 180s

      labels:
        - "traefik.enable=true"
        - "traefik.swarm.network=traefik_public"
        - "traefik.http.routers.taktchat-api.rule=Host(`api.taktchat.com.br`) || Host(`taktchat-api.alivesolucoes.com.br`)"
        - "traefik.http.routers.taktchat-api.entrypoints=websecure"
        - "traefik.http.routers.taktchat-api.tls.certresolver=letsencrypt"
        - "traefik.http.services.taktchat-api.loadbalancer.server.port=8080"
        - "traefik.http.services.taktchat-api.loadbalancer.passHostHeader=true"

    # Healthcheck melhorado (verifica endpoint /health que retorna status de API, DB, etc)
    healthcheck:
      test: ["CMD-SHELL", "node -e \"const http = require('http'); const req = http.get('http://localhost:8080/health', (res) => { let data = ''; res.on('data', (chunk) => { data += chunk; }); res.on('end', () => { try { const json = JSON.parse(data); if (json.status === 'ok' && json.api && json.api.status === 'ok' && json.database && json.database.status === 'ok') { process.exit(0); } else { console.error('Healthcheck failed:', JSON.stringify(json)); process.exit(1); } } catch (e) { console.error('Healthcheck parse error:', e.message); process.exit(1); } }); }); req.on('error', (e) => { console.error('Healthcheck error:', e.message); process.exit(1); }); req.setTimeout(8000, () => { req.destroy(); process.exit(1); });\""]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s

  taktchat-frontend:
    image: node:20-bookworm-slim
    hostname: "{{.Service.Name}}.{{.Task.Slot}}"
    networks:
      - traefik_public
    volumes:
      - /root/taktchat/frontend:/usr/src/app  # Código do frontend
      - taktchat_frontend_node_modules:/usr/src/app/node_modules  # Dependências isoladas
      - /root/stacks/scripts/taktchat-frontend-startup.sh:/usr/local/bin/taktchat-frontend-startup.sh:ro  # Script de startup
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
      - REACT_APP_BACKEND_URL=https://api.taktchat.com.br
      - REACT_APP_SOCKET_URL=https://api.taktchat.com.br
      - REACT_APP_PRIMARY_COLOR=#2563EB
      - REACT_APP_PRIMARY_DARK=#1E3A8A
      - PUBLIC_URL=https://taktchat.com.br
      - GENERATE_SOURCEMAP=false
      - CI=true
      - DISABLE_ESLINT_PLUGIN=true
      - SKIP_PREFLIGHT_CHECK=true
      - PUPPETEER_SKIP_DOWNLOAD=true  # Pular download do Chromium (servidor ARM64)
      - NODE_OPTIONS=--max-old-space-size=8192  # Heap do Node.js para compilação React
    command:
      - /bin/sh
      - /usr/local/bin/taktchat-frontend-startup.sh
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"  # Aumentado para compilação React
          memory: 1024M  # Aumentado para compilação React (build pode usar bastante memória)

      update_config:
        parallelism: 1
        delay: 30s
        order: start-first
        failure_action: pause  # Pausar em caso de falha para análise (não fazer rollback)
        monitor: 60s

      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 2  # Limitar a 2 tentativas para análise de logs
        window: 120s

      labels:
        - "traefik.enable=true"
        - "traefik.swarm.network=traefik_public"
        - "traefik.http.routers.taktchat-app.rule=Host(`taktchat.com.br`) || Host(`taktchat.alivesolucoes.com.br`)"
        - "traefik.http.routers.taktchat-app.entrypoints=websecure"
        - "traefik.http.routers.taktchat-app.tls.certresolver=letsencrypt"
        - "traefik.http.services.taktchat-app.loadbalancer.server.port=3000"
        - "traefik.http.services.taktchat-app.loadbalancer.passHostHeader=true"

networks:
  app_network:
    external: true
  traefik_public:
    external: true

volumes:
  taktchat_media:
    driver: local  # Uploads e arquivos públicos do backend
  taktchat_node_modules:
    driver: local  # Dependências do backend (isoladas)
  taktchat_tsc_cache:
    driver: local  # Cache de compilação TypeScript (hash-based)
  taktchat_frontend_node_modules:
    driver: local  # Dependências do frontend (isoladas)